{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Cloning into 'auto-evaluator'...\n",
      "remote: Enumerating objects: 74, done.\u001b[K\n",
      "remote: Counting objects: 100% (38/38), done.\u001b[K\n",
      "remote: Compressing objects: 100% (28/28), done.\u001b[K\n",
      "remote: Total 74 (delta 17), reused 21 (delta 9), pack-reused 36\u001b[K\n",
      "Receiving objects: 100% (74/74), 44.66 MiB | 19.43 MiB/s, done.\n",
      "Resolving deltas: 100% (27/27), done.\n"
     ]
    }
   ],
   "source": [
    "!git clone https://github.com/PineappleExpress808/auto-evaluator\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/Users/takeshiiijima/github/chat-gpt-samples/013.auto_evaluato/auto-evaluator\n"
     ]
    }
   ],
   "source": [
    "%cd auto-evaluator"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting pandas==1.4.3\n",
      "  Downloading pandas-1.4.3-cp39-cp39-macosx_10_9_x86_64.whl (11.5 MB)\n",
      "\u001b[K     |████████████████████████████████| 11.5 MB 610 kB/s eta 0:00:01\n",
      "\u001b[?25hCollecting fastapi==0.85.2\n",
      "  Using cached fastapi-0.85.2-py3-none-any.whl (55 kB)\n",
      "Collecting langchain==0.0.141\n",
      "  Using cached langchain-0.0.141-py3-none-any.whl (540 kB)\n",
      "Collecting python-multipart==0.0.6\n",
      "  Using cached python_multipart-0.0.6-py3-none-any.whl (45 kB)\n",
      "Collecting uvicorn==0.18.3\n",
      "  Using cached uvicorn-0.18.3-py3-none-any.whl (57 kB)\n",
      "Collecting openai==0.27.0\n",
      "  Using cached openai-0.27.0-py3-none-any.whl (70 kB)\n",
      "Collecting tiktoken==0.3.1\n",
      "  Downloading tiktoken-0.3.1-cp39-cp39-macosx_10_9_x86_64.whl (735 kB)\n",
      "\u001b[K     |████████████████████████████████| 735 kB 27.0 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting faiss-cpu==1.7.3\n",
      "  Downloading faiss_cpu-1.7.3-cp39-cp39-macosx_10_9_x86_64.whl (5.6 MB)\n",
      "\u001b[K     |████████████████████████████████| 5.6 MB 29.8 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting huggingface-hub==0.12.0\n",
      "  Using cached huggingface_hub-0.12.0-py3-none-any.whl (190 kB)\n",
      "Collecting anthropic==0.2.6\n",
      "  Using cached anthropic-0.2.6-py3-none-any.whl (6.4 kB)\n",
      "Collecting llama-cpp-python==0.1.32\n",
      "  Using cached llama_cpp_python-0.1.32.tar.gz (1.1 MB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25ldone\n",
      "\u001b[?25h    Preparing wheel metadata ... \u001b[?25ldone\n",
      "\u001b[?25hCollecting pypdf==3.7.1\n",
      "  Using cached pypdf-3.7.1-py3-none-any.whl (248 kB)\n",
      "Collecting filetype==1.2.0\n",
      "  Using cached filetype-1.2.0-py2.py3-none-any.whl (19 kB)\n",
      "Requirement already satisfied: altair==4.2.2 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from -r requirements.txt (line 14)) (4.2.2)\n",
      "Collecting tokenizers==0.13.3\n",
      "  Downloading tokenizers-0.13.3-cp39-cp39-macosx_10_11_x86_64.whl (4.0 MB)\n",
      "\u001b[K     |████████████████████████████████| 4.0 MB 23.4 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting sentence-transformers==2.2.2\n",
      "  Using cached sentence-transformers-2.2.2.tar.gz (85 kB)\n",
      "Collecting scikit-learn==1.2.1\n",
      "  Downloading scikit_learn-1.2.1-cp39-cp39-macosx_10_9_x86_64.whl (9.1 MB)\n",
      "\u001b[K     |████████████████████████████████| 9.1 MB 13.7 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting llama-index==0.4.35.post1\n",
      "  Using cached llama_index-0.4.35.post1.tar.gz (149 kB)\n",
      "\u001b[31mERROR: Could not find a version that satisfies the requirement streamlit==1.21.0 (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.8.2, 0.9.0, 0.11.0, 0.12.2, 0.12.3, 0.12.4, 0.13.0, 0.13.1, 0.13.3, 0.13.5, 0.14.2, 0.15.0, 0.15.1, 0.15.2, 0.15.3, 0.15.4, 0.15.5, 0.15.6, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.17.0, 0.17.1, 0.17.2, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 0.20.0, 0.21.0, 0.22.0, 0.22.1, 0.22.2, 0.23.0, 0.24.0, 0.24.1, 0.24.2, 0.24.3, 0.25.0, 0.26.0, 0.26.1, 0.27.0, 0.28.0, 0.29.0, 0.30.0, 0.31.0, 0.32.0, 0.33.0, 0.34.0, 0.35.0, 0.36.0, 0.37.0, 0.40.0, 0.40.1, 0.41.0, 0.42.0, 0.43.0, 0.43.1, 0.43.2, 0.44.0, 0.45.0, 0.46.0, 0.47.0, 0.47.1, 0.47.2, 0.47.3, 0.47.4, 0.48.0, 0.48.1, 0.49.0, 0.50.0, 0.50.1, 0.50.2, 0.51.0, 0.52.0, 0.52.1, 0.52.2, 0.53.0, 0.54.0, 0.55.0, 0.56.0, 0.57.0, 0.57.1, 0.57.2, 0.57.3, 0.58.0, 0.59.0, 0.60.0, 0.61.0, 0.62.0, 0.62.1, 0.63.0, 0.63.1, 0.64.0, 0.65.0, 0.65.1, 0.65.2, 0.66.0, 0.67.0, 0.67.1, 0.68.0, 0.68.1, 0.69.0, 0.69.1, 0.69.2, 0.70.0, 0.71.0, 0.72.0, 0.73.0, 0.73.1, 0.74.0, 0.74.1, 0.75.0, 0.76.0, 0.77.0, 0.78.0, 0.79.0, 0.80.0, 0.81.0, 0.81.1, 0.82.0, 0.83.0, 0.84.0, 0.84.1, 0.84.2, 0.85.0, 0.85.1, 0.86.0, 0.87.0, 0.88.0, 0.89.0, 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.4.0, 1.5.0, 1.5.1, 1.6.0rc3, 1.6.0rc4, 1.6.0, 1.7.0, 1.8.0rc1, 1.8.0, 1.8.1rc1, 1.8.1, 1.9.0rc1, 1.9.0, 1.9.1rc1, 1.9.1rc2, 1.9.1, 1.9.2rc1, 1.9.2, 1.10.0rc1, 1.10.0rc2, 1.10.0, 1.11.0rc1, 1.11.0, 1.11.1rc1, 1.11.1, 1.12.0rc1, 1.12.0rc2, 1.12.0)\u001b[0m\n",
      "\u001b[31mERROR: No matching distribution found for streamlit==1.21.0\u001b[0m\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "%pip install -r requirements.txt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: streamlit in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (1.12.0)\n",
      "Requirement already satisfied: numpy in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from streamlit) (1.20.3)\n",
      "Requirement already satisfied: cachetools>=4.0 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from streamlit) (5.3.0)\n",
      "Requirement already satisfied: altair>=3.2.0 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from streamlit) (4.2.2)\n",
      "Requirement already satisfied: importlib-metadata>=1.4 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from streamlit) (4.8.1)\n",
      "Requirement already satisfied: requests>=2.4 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from streamlit) (2.26.0)\n",
      "Requirement already satisfied: typing-extensions>=3.10.0.0 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from streamlit) (4.5.0)\n",
      "Requirement already satisfied: pyarrow>=4.0 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from streamlit) (11.0.0)\n",
      "Requirement already satisfied: rich>=10.11.0 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from streamlit) (13.3.4)\n",
      "Requirement already satisfied: pillow>=6.2.0 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from streamlit) (8.4.0)\n",
      "Requirement already satisfied: pandas>=0.21.0 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from streamlit) (1.3.4)\n",
      "Requirement already satisfied: validators>=0.2 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from streamlit) (0.20.0)\n",
      "Requirement already satisfied: toml in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from streamlit) (0.10.2)\n",
      "Requirement already satisfied: click>=7.0 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from streamlit) (8.0.3)\n",
      "Requirement already satisfied: tornado>=5.0 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from streamlit) (6.1)\n",
      "Requirement already satisfied: gitpython!=3.1.19 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from streamlit) (3.1.31)\n",
      "Requirement already satisfied: packaging>=14.1 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from streamlit) (21.0)\n",
      "Requirement already satisfied: python-dateutil in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from streamlit) (2.8.2)\n",
      "Requirement already satisfied: semver in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from streamlit) (3.0.0)\n",
      "Requirement already satisfied: tzlocal>=1.1 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from streamlit) (4.3)\n",
      "Requirement already satisfied: pydeck>=0.1.dev5 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from streamlit) (0.8.1b0)\n",
      "Requirement already satisfied: protobuf<4,>=3.12 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from streamlit) (3.20.3)\n",
      "Requirement already satisfied: pympler>=0.9 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from streamlit) (1.0.1)\n",
      "Requirement already satisfied: blinker>=1.0.0 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from streamlit) (1.6.2)\n",
      "Requirement already satisfied: toolz in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from altair>=3.2.0->streamlit) (0.11.1)\n",
      "Requirement already satisfied: jinja2 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from altair>=3.2.0->streamlit) (2.11.3)\n",
      "Requirement already satisfied: jsonschema>=3.0 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from altair>=3.2.0->streamlit) (3.2.0)\n",
      "Requirement already satisfied: entrypoints in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from altair>=3.2.0->streamlit) (0.3)\n",
      "Requirement already satisfied: gitdb<5,>=4.0.1 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from gitpython!=3.1.19->streamlit) (4.0.10)\n",
      "Requirement already satisfied: smmap<6,>=3.0.1 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19->streamlit) (5.0.0)\n",
      "Requirement already satisfied: zipp>=0.5 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from importlib-metadata>=1.4->streamlit) (3.6.0)\n",
      "Requirement already satisfied: attrs>=17.4.0 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from jsonschema>=3.0->altair>=3.2.0->streamlit) (21.2.0)\n",
      "Requirement already satisfied: six>=1.11.0 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from jsonschema>=3.0->altair>=3.2.0->streamlit) (1.16.0)\n",
      "Requirement already satisfied: pyrsistent>=0.14.0 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from jsonschema>=3.0->altair>=3.2.0->streamlit) (0.18.0)\n",
      "Requirement already satisfied: setuptools in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from jsonschema>=3.0->altair>=3.2.0->streamlit) (58.0.4)\n",
      "Requirement already satisfied: pyparsing>=2.0.2 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from packaging>=14.1->streamlit) (3.0.4)\n",
      "Requirement already satisfied: pytz>=2017.3 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from pandas>=0.21.0->streamlit) (2021.3)\n",
      "Requirement already satisfied: MarkupSafe>=0.23 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from jinja2->altair>=3.2.0->streamlit) (1.1.1)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from requests>=2.4->streamlit) (3.2)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from requests>=2.4->streamlit) (1.26.7)\n",
      "Requirement already satisfied: charset-normalizer~=2.0.0 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from requests>=2.4->streamlit) (2.0.4)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from requests>=2.4->streamlit) (2021.10.8)\n",
      "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from rich>=10.11.0->streamlit) (2.15.1)\n",
      "Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from rich>=10.11.0->streamlit) (2.2.0)\n",
      "Requirement already satisfied: mdurl~=0.1 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich>=10.11.0->streamlit) (0.1.2)\n",
      "Requirement already satisfied: pytz-deprecation-shim in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from tzlocal>=1.1->streamlit) (0.1.0.post0)\n",
      "Requirement already satisfied: decorator>=3.4.0 in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from validators>=0.2->streamlit) (5.1.0)\n",
      "Requirement already satisfied: tzdata in /Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages (from pytz-deprecation-shim->tzlocal>=1.1->streamlit) (2023.3)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "%pip install streamlit"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2023-04-19 07:57:23.468 INFO    numexpr.utils: NumExpr defaulting to 8 threads.\n",
      "\u001b[0m\n",
      "\u001b[34m\u001b[1m  You can now view your Streamlit app in your browser.\u001b[0m\n",
      "\u001b[0m\n",
      "\u001b[34m  Local URL: \u001b[0m\u001b[1mhttp://localhost:8501\u001b[0m\n",
      "\u001b[34m  Network URL: \u001b[0m\u001b[1mhttp://192.168.0.7:8501\u001b[0m\n",
      "\u001b[0m\n",
      "2023-04-19 07:57:29.406 Uncaught exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/http1connection.py\", line 273, in _read_message\n",
      "    delegate.finish()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/routing.py\", line 268, in finish\n",
      "    self.delegate.finish()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 2290, in finish\n",
      "    self.execute()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 2309, in execute\n",
      "    self.handler = self.handler_class(\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/websocket.py\", line 224, in __init__\n",
      "    super().__init__(application, request, **kwargs)\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 209, in __init__\n",
      "    super().__init__()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/typing.py\", line 1083, in _no_init\n",
      "    raise TypeError('Protocols cannot be instantiated')\n",
      "TypeError: Protocols cannot be instantiated\n",
      "2023-04-19 07:57:29.424 Uncaught exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/http1connection.py\", line 273, in _read_message\n",
      "    delegate.finish()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/routing.py\", line 268, in finish\n",
      "    self.delegate.finish()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 2290, in finish\n",
      "    self.execute()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 2309, in execute\n",
      "    self.handler = self.handler_class(\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/websocket.py\", line 224, in __init__\n",
      "    super().__init__(application, request, **kwargs)\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 209, in __init__\n",
      "    super().__init__()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/typing.py\", line 1083, in _no_init\n",
      "    raise TypeError('Protocols cannot be instantiated')\n",
      "TypeError: Protocols cannot be instantiated\n",
      "2023-04-19 07:57:29.439 Uncaught exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/http1connection.py\", line 273, in _read_message\n",
      "    delegate.finish()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/routing.py\", line 268, in finish\n",
      "    self.delegate.finish()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 2290, in finish\n",
      "    self.execute()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 2309, in execute\n",
      "    self.handler = self.handler_class(\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/websocket.py\", line 224, in __init__\n",
      "    super().__init__(application, request, **kwargs)\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 209, in __init__\n",
      "    super().__init__()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/typing.py\", line 1083, in _no_init\n",
      "    raise TypeError('Protocols cannot be instantiated')\n",
      "TypeError: Protocols cannot be instantiated\n",
      "2023-04-19 07:57:29.456 Uncaught exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/http1connection.py\", line 273, in _read_message\n",
      "    delegate.finish()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/routing.py\", line 268, in finish\n",
      "    self.delegate.finish()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 2290, in finish\n",
      "    self.execute()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 2309, in execute\n",
      "    self.handler = self.handler_class(\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/websocket.py\", line 224, in __init__\n",
      "    super().__init__(application, request, **kwargs)\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 209, in __init__\n",
      "    super().__init__()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/typing.py\", line 1083, in _no_init\n",
      "    raise TypeError('Protocols cannot be instantiated')\n",
      "TypeError: Protocols cannot be instantiated\n",
      "2023-04-19 07:57:29.473 Uncaught exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/http1connection.py\", line 273, in _read_message\n",
      "    delegate.finish()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/routing.py\", line 268, in finish\n",
      "    self.delegate.finish()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 2290, in finish\n",
      "    self.execute()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 2309, in execute\n",
      "    self.handler = self.handler_class(\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/websocket.py\", line 224, in __init__\n",
      "    super().__init__(application, request, **kwargs)\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 209, in __init__\n",
      "    super().__init__()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/typing.py\", line 1083, in _no_init\n",
      "    raise TypeError('Protocols cannot be instantiated')\n",
      "TypeError: Protocols cannot be instantiated\n",
      "2023-04-19 07:57:29.489 Uncaught exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/http1connection.py\", line 273, in _read_message\n",
      "    delegate.finish()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/routing.py\", line 268, in finish\n",
      "    self.delegate.finish()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 2290, in finish\n",
      "    self.execute()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 2309, in execute\n",
      "    self.handler = self.handler_class(\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/websocket.py\", line 224, in __init__\n",
      "    super().__init__(application, request, **kwargs)\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 209, in __init__\n",
      "    super().__init__()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/typing.py\", line 1083, in _no_init\n",
      "    raise TypeError('Protocols cannot be instantiated')\n",
      "TypeError: Protocols cannot be instantiated\n",
      "2023-04-19 07:57:29.505 Uncaught exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/http1connection.py\", line 273, in _read_message\n",
      "    delegate.finish()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/routing.py\", line 268, in finish\n",
      "    self.delegate.finish()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 2290, in finish\n",
      "    self.execute()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 2309, in execute\n",
      "    self.handler = self.handler_class(\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/websocket.py\", line 224, in __init__\n",
      "    super().__init__(application, request, **kwargs)\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 209, in __init__\n",
      "    super().__init__()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/typing.py\", line 1083, in _no_init\n",
      "    raise TypeError('Protocols cannot be instantiated')\n",
      "TypeError: Protocols cannot be instantiated\n",
      "2023-04-19 07:57:29.528 Uncaught exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/http1connection.py\", line 273, in _read_message\n",
      "    delegate.finish()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/routing.py\", line 268, in finish\n",
      "    self.delegate.finish()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 2290, in finish\n",
      "    self.execute()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 2309, in execute\n",
      "    self.handler = self.handler_class(\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/websocket.py\", line 224, in __init__\n",
      "    super().__init__(application, request, **kwargs)\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 209, in __init__\n",
      "    super().__init__()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/typing.py\", line 1083, in _no_init\n",
      "    raise TypeError('Protocols cannot be instantiated')\n",
      "TypeError: Protocols cannot be instantiated\n",
      "2023-04-19 07:57:29.578 Uncaught exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/http1connection.py\", line 273, in _read_message\n",
      "    delegate.finish()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/routing.py\", line 268, in finish\n",
      "    self.delegate.finish()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 2290, in finish\n",
      "    self.execute()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 2309, in execute\n",
      "    self.handler = self.handler_class(\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/websocket.py\", line 224, in __init__\n",
      "    super().__init__(application, request, **kwargs)\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 209, in __init__\n",
      "    super().__init__()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/typing.py\", line 1083, in _no_init\n",
      "    raise TypeError('Protocols cannot be instantiated')\n",
      "TypeError: Protocols cannot be instantiated\n",
      "2023-04-19 07:57:29.636 Uncaught exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/http1connection.py\", line 273, in _read_message\n",
      "    delegate.finish()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/routing.py\", line 268, in finish\n",
      "    self.delegate.finish()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 2290, in finish\n",
      "    self.execute()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 2309, in execute\n",
      "    self.handler = self.handler_class(\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/websocket.py\", line 224, in __init__\n",
      "    super().__init__(application, request, **kwargs)\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 209, in __init__\n",
      "    super().__init__()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/typing.py\", line 1083, in _no_init\n",
      "    raise TypeError('Protocols cannot be instantiated')\n",
      "TypeError: Protocols cannot be instantiated\n",
      "2023-04-19 07:57:29.689 Uncaught exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/http1connection.py\", line 273, in _read_message\n",
      "    delegate.finish()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/routing.py\", line 268, in finish\n",
      "    self.delegate.finish()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 2290, in finish\n",
      "    self.execute()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 2309, in execute\n",
      "    self.handler = self.handler_class(\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/websocket.py\", line 224, in __init__\n",
      "    super().__init__(application, request, **kwargs)\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 209, in __init__\n",
      "    super().__init__()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/typing.py\", line 1083, in _no_init\n",
      "    raise TypeError('Protocols cannot be instantiated')\n",
      "TypeError: Protocols cannot be instantiated\n",
      "2023-04-19 07:57:29.847 Uncaught exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/http1connection.py\", line 273, in _read_message\n",
      "    delegate.finish()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/routing.py\", line 268, in finish\n",
      "    self.delegate.finish()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 2290, in finish\n",
      "    self.execute()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 2309, in execute\n",
      "    self.handler = self.handler_class(\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/websocket.py\", line 224, in __init__\n",
      "    super().__init__(application, request, **kwargs)\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 209, in __init__\n",
      "    super().__init__()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/typing.py\", line 1083, in _no_init\n",
      "    raise TypeError('Protocols cannot be instantiated')\n",
      "TypeError: Protocols cannot be instantiated\n",
      "2023-04-19 07:57:30.460 Uncaught exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/http1connection.py\", line 273, in _read_message\n",
      "    delegate.finish()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/routing.py\", line 268, in finish\n",
      "    self.delegate.finish()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 2290, in finish\n",
      "    self.execute()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 2309, in execute\n",
      "    self.handler = self.handler_class(\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/websocket.py\", line 224, in __init__\n",
      "    super().__init__(application, request, **kwargs)\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 209, in __init__\n",
      "    super().__init__()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/typing.py\", line 1083, in _no_init\n",
      "    raise TypeError('Protocols cannot be instantiated')\n",
      "TypeError: Protocols cannot be instantiated\n",
      "2023-04-19 07:57:31.180 Uncaught exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/http1connection.py\", line 273, in _read_message\n",
      "    delegate.finish()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/routing.py\", line 268, in finish\n",
      "    self.delegate.finish()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 2290, in finish\n",
      "    self.execute()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 2309, in execute\n",
      "    self.handler = self.handler_class(\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/websocket.py\", line 224, in __init__\n",
      "    super().__init__(application, request, **kwargs)\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 209, in __init__\n",
      "    super().__init__()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/typing.py\", line 1083, in _no_init\n",
      "    raise TypeError('Protocols cannot be instantiated')\n",
      "TypeError: Protocols cannot be instantiated\n",
      "2023-04-19 07:57:51.055 Uncaught exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/http1connection.py\", line 273, in _read_message\n",
      "    delegate.finish()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/routing.py\", line 268, in finish\n",
      "    self.delegate.finish()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 2290, in finish\n",
      "    self.execute()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 2309, in execute\n",
      "    self.handler = self.handler_class(\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/websocket.py\", line 224, in __init__\n",
      "    super().__init__(application, request, **kwargs)\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py\", line 209, in __init__\n",
      "    super().__init__()\n",
      "  File \"/Users/takeshiiijima/opt/anaconda3/lib/python3.9/typing.py\", line 1083, in _no_init\n",
      "    raise TypeError('Protocols cannot be instantiated')\n",
      "TypeError: Protocols cannot be instantiated\n",
      "^C\n",
      "\u001b[34m  Stopping...\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "# Note : run on terminal\n",
    "# !streamlit run auto-evaluator.py\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "ba4685d77e38b324b783c99f55a40dcfa1c007f9b49c957ce0db47751e3049b4"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
